element-hq/ess-helm

artifacthub-repo.yaml
docs/advanced.md
newsfragments/334.internal.md

https://artifacthub.io/packages/helm/element-server-suite-community/matrix-stack
This fixes the exclusion of all dev versions :

artifacthub: fix regex + package url / repo ID

---

newsfragments/338.internal.md
tests/manifests/test_configs_and_mounts_consistency.py

- We need to filter only mounted subPath when looking in configMap content
- We need to look into the render-config container for source config maps

enhance mount path detection with render-config

---

charts/matrix-stack/ci/fragments/init-secrets-disabled.yaml
charts/matrix-stack/ci/matrix-authentication-service-postgres-secrets-externally-values.yaml
charts/matrix-stack/ci/matrix-authentication-service-postgres-secrets-in-helm-values.yaml
charts/matrix-stack/ci/synapse-postgres-secrets-externally-values.yaml
charts/matrix-stack/ci/synapse-postgres-secrets-in-helm-values.yaml
charts/matrix-stack/ci/well-known-minimal-values.yaml
charts/matrix-stack/templates/ess-library/_credentials.tpl
charts/matrix-stack/templates/postgres/_postgres_secret.tpl
newsfragments/342.fixed.md

Without the fix, the new CI values discovered : 
```
engine.go:227: [INFO] Fail: check-credential: initSecrets is disabled, but the Secret configuration at postgres.essPasswords.synapse is not present
engine.go:227: [INFO] Fail: check-credential: initSecrets is disabled, but the Secret configuration at postgres.essPasswords.synapse is not present
engine.go:227: [INFO] Fail: check-credential: initSecrets is disabled, but the Secret configuration at postgres.essPasswords.synapse is not present
engine.go:227: [INFO] Fail: check-credential: initSecrets is disabled, but the Secret configuration at postgres.essPasswords.synapse is not present
engine.go:227: [INFO] Fail: check-credential: initSecrets is disabled, but the Secret configuration at postgres.essPasswords.matrixAuthenticationService …
```

postgres password: generate only required passwords

---

charts/matrix-stack/templates/synapse/_helpers.tpl
newsfragments/345.fixed.md

Minor template issue but could case persisters to loop replicate requests to themselves.

synapse: fix APPLICATION_NAME template

---

charts/matrix-stack/source/common/sub_schema_values.yaml.j2
charts/matrix-stack/values.yaml
matrix-tools/cmd/main.go
newsfragments/350.fixed.md

Required for Matrix-RTC SFU to stop complaining about others permissions : 
`2025-04-04T15:48:02.942538481Z stdout F key file others permissions must be set to 0`

Matrix-Tools: Stricter rendered file permissions

---

charts/matrix-stack/configs/matrix-rtc/sfu/config.yaml.tpl
charts/matrix-stack/templates/matrix-rtc/_helpers.tpl
charts/matrix-stack/templates/matrix-rtc/ingress.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_secret.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_service.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_service_monitor.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_serviceaccount.yaml
tests/integration/test_element_call.py
tests/manifests/__init__.py
tests/manifests/test_ingresses.py

- Rename `sfu-jwt` to `sfu-authorizer`
- Remove the ci values override mechanism in the manifest tests
- Fix the matrix-rtc ingress labels

matrix-rtc: rationalize names

---

charts/matrix-stack/templates/synapse/_synapse_config.tpl
newsfragments/374.changed.md

Technically an empty list does work as each listener will contain a health endpoint (except apparently not metrics). Being explicit though avoids confusion on what this particular listener is for.

Synapse: Make health listener resource name explicit

---

charts/matrix-stack/templates/synapse/_synapse_config.tpl
newsfragments/375.changed.md

This is added by Synapse internally (https://github.com/element-hq/synapse/blob/develop/synapse/config/server.py#L329-L337) but we can be explicit here in our config to match Synapse documentation config examples.

Synapse: Add trailing slash to public_baseurl

---

charts/matrix-stack/templates/element-web/deployment.yaml
charts/matrix-stack/templates/synapse/synapse_check_config_job_hook.yaml
charts/matrix-stack/templates/synapse/synapse_statefulset.yaml
newsfragments/379.changed.md
tests/manifests/test_labels.py

i.e. `{Deployment,StatefulSet.Job}.metadata.labels` is the same as `spec.template.metadata.labels` with the exception of `helm.sh/chart` which must be missing from the Pod spec

Ensure pods have the same labels as their parents

---

charts/matrix-stack/templates/element-web/deployment.yaml
charts/matrix-stack/templates/ess-library/_labels.tpl
charts/matrix-stack/templates/haproxy/deployment.yaml
charts/matrix-stack/templates/matrix-authentication-service/deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_deployment.yaml
charts/matrix-stack/templates/postgres/statefulset.yaml
charts/matrix-stack/templates/synapse/_synapse_pod.tpl
charts/matrix-stack/templates/synapse/redis_deployment.yaml
charts/matrix-stack/templates/synapse/synapse_check_config_job_hook.yaml
charts/matrix-stack/templates/synapse/synapse_statefulset.yaml
newsfragments/380.changed.1.md
newsfragments/380.changed.md
tests/manifests/test_annotations.py
tests/manifests/test_labels.py

Before:
```sh
$ ack k8s.element.io charts | sed 's/.*k8s/k8s/' | sed 's/: .*//' | sort | uniq -c
6 k8s.element.io/as-registration-{{ $index }}-hash
3 k8s.element.io/configdatahash
12 k8s.element.io/confighash
2 k8s.element.io/nginxhash
1 k8s.element.io/postgresPasswordHash
3 k8s.element.io/secretdatahash
6 k8s.element.io/secrethash
2 k8s.element.io/synapsehash
5 k8s.element.io/synapse-instance
2 k8s.element.io/target-instance
2 k8s.element.io/target-name
2 k8s.element.io/wellknowndelegationhash
```
After:
```sh
ack k8s.element.io charts | sed 's/.*k8s/k8s/' | sed 's/: .*//' | sort | uniq -c
6 k8s.element.io/as-registration-{{ $index }}-hash
2 k8s.element.io/element-web-config-hash
2 k8s.element.io/matrix-authentication-service-config-hash
2 …
```

Enforce label naming consistency

---

.github/workflows/build-test.yml
.github/workflows/pytest.yml
newsfragments/388.internal.1.md
newsfragments/388.internal.md

* Pick up new integration tests without changing the workflow file
* Run the manifest tests in parallel

Make PyTests run dynamically

---

tests/manifests/test_pod_env.py

if a values file has a `extraEnv` already, we want to override it.

fix extraEnv values_fragment

---

.github/workflows/scripts-linting.yml
newsfragments/409.internal.md
poetry.lock
pyproject.toml
tests/manifests/__init__.py
tests/manifests/test_service_monitors.py
tests/manifests/utils.py

Add some static type checking of the manifest tests.
Also a drive-by minor change to default more of the `has_` variables based on `has_workloads`

Manifest test type checking

---

charts/matrix-stack/templates/matrix-authentication-service/deployment.yaml
newsfragments/416.changed.md

This moves the DB migration step to a dedicated init container, instead of doing it on startup of the main container which could potentially take long & fail liveness checks.
With that said, in practice we haven't seen a MAS deployment so large that its DB migration took long enough to fail liveness checks, so using an init container is more of a best-practice than a hard necessity.

Matrix Authentication Service: migrate DB on init

---

newsfragments/418.internal.md
pyproject.toml
tests/integration/fixtures/cluster.py
tests/manifests/__init__.py
tests/manifests/test_matrix_rtc.py
tests/manifests/test_pod_pull_secrets.py
tests/manifests/test_serviceaccounts.py
tests/manifests/utils.py

The final commit (the ServiceAccount manifest test change) is the most important here as it makes the test dependent on the order of `DeployableDetails`

Small manifest test fixes

---

newsfragments/420.internal.md
tests/manifests/__init__.py
tests/manifests/test_element_web.py
tests/manifests/test_ingresses.py
tests/manifests/test_labels.py
tests/manifests/test_matrix_authentication_service.py
tests/manifests/test_matrix_rtc.py
tests/manifests/test_pod_env.py
tests/manifests/test_pod_pull_secrets.py
tests/manifests/test_pod_securityContext.py
tests/manifests/test_postgres.py
tests/manifests/test_service_monitors.py
tests/manifests/test_serviceaccounts.py
tests/manifests/test_synapse.py
tests/manifests/test_tolerations.py
tests/manifests/test_topology_spread_constraints.py
tests/manifests/test_well_known_delegation.py
tests/manifests/utils.py

We want to be able to test properties about sidecars after varying their properties. This means that they need to be sub-classes of `DeployableDetails` so that the various `iterate_deployables_(foo_)?parts` methods can work on them. We also have situations where sub-component or sidecar has e.g. env/images but they aren't controllable through its own properties (the check config hook having properties from Synapse) or might not be in quite the expected place. Given a `iterate_deployables_(foo_)?parts` visitor can & does modify multiple different properties (e.g. `serviceMonitors` and `labels`), we can't push that logic down into every test, so we have to unify the setting of properties inside `DeployableDetails`.
We can use the same mechanism to get rid of the awkward …

Make it possible to manifest test sidecars properly

---

charts/matrix-stack/source/haproxy.json
charts/matrix-stack/source/init-secrets.json
charts/matrix-stack/source/postgres.json
charts/matrix-stack/source/synapse.json
charts/matrix-stack/templates/haproxy/deployment.yaml
charts/matrix-stack/templates/init-secrets/_helpers.tpl
charts/matrix-stack/templates/init-secrets/job.yaml
charts/matrix-stack/templates/postgres/_helpers.tpl
charts/matrix-stack/templates/postgres/statefulset.yaml
charts/matrix-stack/templates/synapse/redis_deployment.yaml
charts/matrix-stack/values.schema.json
newsfragments/421.changed.md
tests/manifests/__init__.py
tests/manifests/test_pod_env.py

We don't gain much from disallowing `extraEnv` on specific components, it just complicates our tests. Support it on all components so that we can test it on all components

Support extraEnv on every workload

---

.github/workflows/actions-linting.yml
.github/workflows/build-test.yml
newsfragments/431.internal.md

It is often unclear what the impact of changes are. Run through all the CI files generating all the templates for both source and target branches and compare the 2.

Add a job to compare generated templates between source and target branches

---

charts/matrix-stack/templates/haproxy/deployment.yaml
newsfragments/437.changed.md

We always want a `startupProbe` for HAProxy. We also always want to use named ports (so that changing the port number doesn't cause breakages in the probes.
The `periodSeconds` and `failureThreshold` are going to be extreme with no Synapse but this is a problem after #430 that we push onto users.
Doing as a separate PR to minimise `dyff` & increase reviewability

HAProxy startupProbe and named ports

---

charts/matrix-stack/templates/synapse/synapse_statefulset.yaml
newsfragments/438.fixed.md
tests/manifests/test_synapse.py
tests/manifests/utils.py

Discovered when looking at #430 that worker probe values weren't overriding "shared" (main process) values. This was because `$perProcessRoot` was being passed into `element-io.synapse.pod-template` which didn't include `synapse.workers.<worker name>` values.
Remove the split variable and simply make the context the full merge between `synapse`, `synapse.workers.<worker name>` and the static `processType` & `isHook` variables.
Add tests to assert this

Correctly merge Synapse per-process values that override shared values

---

newsfragments/442.internal.md
tests/integration/artifacts/certs.py

Testing in browser now works fine when importing `~/.cache/pytest-ess/ess-ca.key`

pytest: fix CA cache was regenerated every run

---

.github/workflows/build-test.yml
newsfragments/431.internal.md
newsfragments/436.internal.md
newsfragments/443.internal.md
newsfragments/447.internal.md

#444 set the namespace on `kubeconform` and the new manifests in `template-dyff` but not the base manifests in `template-dyff`. Fix this.
Also rather than renaming release notes, c/p them so that multiple PRs are attached to it

Use the correct namespace on the base branch for `template-dyff` too

---

charts/matrix-stack/configs/matrix-rtc/sfu/config.yaml.tpl
charts/matrix-stack/templates/matrix-rtc/_helpers.tpl
charts/matrix-stack/templates/matrix-rtc/ingress.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_secret.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_service.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_service_monitor.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_serviceaccount.yaml
newsfragments/446.changed.md

It was decided to converge to Matrix RTC Authorisation Service to name the service issuing JWTs.

matrix-rtc: rename authorizer to matrix-rtc-authorisation-service

---

.github/workflows/build-test.yml
newsfragments/450.internal.md

We don't want changes on the target branch since the PR branched off to contribute to the `dyff`

Use most-recent common ancestor as base for `template-dyff` job

---

newsfragments/453.internal.1.md
newsfragments/453.internal.md
tests/manifests/__init__.py
tests/manifests/test_pod_probes.py
tests/manifests/test_pod_pull_secrets.py
tests/manifests/test_pod_resources.py
tests/manifests/test_synapse.py
tests/manifests/utils.py

Treat Synapse workers as sub-components like everything else to remove special casing of them

Support Synapse workers in the manifest tests

---

charts/matrix-stack/configs/element-web/config.json.tpl
newsfragments/456.fixed.md
tests/manifests/test_element_web.py

Based on what was written in the test, this was the intention. Unlike with Synapse or Well-Known Delegation, it probably isn't a huge problem if these properties are overridden. If it does become so we can add an override/underride scheme

Fix Element Web built-in config not being override-able

---

charts/matrix-stack/source/common/sub_schema_values.yaml.j2
charts/matrix-stack/source/element-web.yaml.j2
charts/matrix-stack/source/matrixAuthenticationService.yaml.j2
charts/matrix-stack/source/synapse/synapse_sub_schema_values.yaml.j2
charts/matrix-stack/values.yaml
newsfragments/433.changed.md
tests/manifests/test_pod_probes.py

Builds on #430 but makes the probe thresholds and frequencies explicit even if they're the k8s defaults.

Make probe thresholds and frequencies explicit

---

charts/matrix-stack/source/element-web.yaml.j2
charts/matrix-stack/source/haproxy.yaml.j2
charts/matrix-stack/source/matrixAuthenticationService.yaml.j2
charts/matrix-stack/source/postgres.yaml.j2
charts/matrix-stack/source/synapse.yaml.j2
charts/matrix-stack/values.yaml
newsfragments/434.changed.md
tests/manifests/test_pod_probes.py

The `startupProbe` proves more flexibility than `{liveness,readiness}Probe.initialDelaySeconds` does. We're not stopping people setting it but let's not set it by default

Replace initialDelaySeconds with startup probes

---

charts/matrix-stack/source/synapse.yaml.j2
charts/matrix-stack/values.yaml
newsfragments/458.changed.md

In the schema, templates and tests but not in `values.yaml`

Synapse Redis has extraEnv like everything else

---

newsfragments/465.internal.1.md
newsfragments/465.internal.md
tests/manifests/__init__.py
tests/manifests/test_basic.py
tests/manifests/test_configs_and_mounts_consistency.py
tests/manifests/test_ingresses.py
tests/manifests/test_manifest_test_infrastructure.py
tests/manifests/test_pod_env.py
tests/manifests/test_pod_probes.py
tests/manifests/test_pod_pull_secrets.py
tests/manifests/test_pod_resources.py
tests/manifests/test_pod_securityContext.py
tests/manifests/test_service_monitors.py
tests/manifests/test_serviceaccounts.py
tests/manifests/test_synapse.py
tests/manifests/test_tolerations.py
tests/manifests/test_topology_spread_constraints.py
tests/manifests/test_volumes_mounts.py
tests/manifests/test_well_known_delegation.py
tests/manifests/utils.py

If a values file is added to both `additional_values_files` and `additional_secret_values_files` it is only run for the secret only tests. This was due to https://github.com/element-hq/ess-helm/pull/273 and ends up with us accidentally skipping values files when testing.
Thinking about it further the whole need to know which components are involved in a test was mostly unneeded. The only test which actually cares is `test_ingress_is_expected_host` and by adding a `PropertyType.Enabled` we can fix this (1st commit).
Make `deployables_details` constant and renamed to `all_deployables_details` and simplify the values file set construction so that it is hard to get wrong (2nd commit).
The final commit simplifies all tests that were obtaining `deployables_details` just to …

Fix manifest tests being skipped

---

.github/workflows/licensing.yml
newsfragments/466.internal.md

So that failures are clearly identified in emails.
Also harmonise on `sh` for string comparisons rather than mixing `bash` and `sh`

Have a distinct copyright dates job

---

.github/workflows/pytest.yml
newsfragments/468.internal.md

We're seeing things like `Deployment.apps "ingress-nginx-controller" is invalid: spec.progressDeadlineSeconds: Invalid value: 0: must be greater than minReadySeconds` on some pytest runs same as https://github.com/helm/helm/issues/30878

Pin Helm to 3.17.3

---

newsfragments/471.internal.md
tests/manifests/test_volumes_mounts.py

This is a kubernetes requirement.

tests: Verify that volume names in workloads specs are not too long

---

newsfragments/480.internal.md
tests/manifests/test_configs.py

The only catches the chart controlled YAML/JSON (which includes user additional that's supplied in the Helm values file). It doesn't check the merged output but given `render-config` needs valid input this is fine

Add manifest test to ensure YAML/JSON written to ConfigMaps and Secrets is valid

---

charts/matrix-stack/configs/synapse/synapse-04-homeserver-overrides.yaml.tpl
charts/matrix-stack/source/common/postgres-libpq.json
charts/matrix-stack/source/common/sub_schema_values.yaml.j2
charts/matrix-stack/templates/ess-library/_labels.tpl
charts/matrix-stack/templates/matrix-authentication-service/_helpers.tpl
charts/matrix-stack/templates/synapse/_synapse_secret.tpl
charts/matrix-stack/values.schema.json
charts/matrix-stack/values.yaml
newsfragments/485.changed.md

Add validation on the external Postgres details via schema so that all Postgres using components get the same level of validation. i.e. MAS wasn't validating `host`/`database`/`user` for external Postgres

Validate external Postgres via schema

---

charts/matrix-stack/source/common/image.json
charts/matrix-stack/templates/element-web/deployment.yaml
charts/matrix-stack/templates/ess-library/_labels.tpl
charts/matrix-stack/templates/haproxy/deployment.yaml
charts/matrix-stack/templates/init-secrets/job.yaml
charts/matrix-stack/templates/matrix-authentication-service/deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_jwt_deployment.yaml
charts/matrix-stack/templates/synapse/_synapse_pod.tpl
charts/matrix-stack/templates/synapse/redis_deployment.yaml
charts/matrix-stack/values.schema.json
newsfragments/484.changed.md
newsfragments/484.internal.md
tests/manifests/__init__.py
tests/manifests/test_labels.py
tests/manifests/test_pod_images.py
tests/manifests/test_pod_probes.py
tests/manifests/test_pod_resources.py

Enforce setting the image tag and/or image digest in the schema. It is not acceptable to unset both.
The 1st commit is an internal test refactor to allow us to read Helm values from elsewhere in the values file. This means that sub-components and sidecars can now express that they don't support setting e.g. images themselves but they do have an image sourced from the parent component. This means that the manifest tests don't need to construct mappings of `DeployableDetails` to expected values, they can simply be fetched. Several tests are simplified and some exceptions removed as a result
The 2nd commit does the schema tightening and adds a test that images are passed through correctly

Image validation via schema

---

newsfragments/500.internal.md
tests/manifests/test_configs_and_mounts_consistency.py
tests/manifests/test_pod_containers_ports.py
tests/manifests/test_pod_pull_secrets.py
tests/manifests/test_pod_securityContext.py
tests/manifests/test_secrets.py
tests/manifests/test_serviceaccounts.py
tests/manifests/test_services.py
tests/manifests/test_tolerations.py
tests/manifests/test_topology_spread_constraints.py

Rough rule of thumb is that I've kept an intermediate variable if used > 2 times

Consistently use template_id helper for identifying manifests.

---

.github/workflows/pytest.yml
newsfragments/502.internal.md

If not specified `latest` is used. https://github.com/Azure/setup-helm/blob/main/src/run.ts#L50-L61 fetches the version from https://get.helm.sh/helm-latest-version:
```sh
$ curl https://get.helm.sh/helm-latest-version
v3.18.1
```

Unpin from Helm 3.17.3

---

charts/matrix-stack/templates/matrix-rtc/ingress.yaml
newsfragments/514.fixed.md

According to https://github.com/element-hq/element-call/blob/livekit/docs/self-hosting.md#matrix-site-endpoint-routing

SFU: Fix ingress needs to set proxy-timeouts and disable buffering

---

.github/workflows/matrix-tools.yml
newsfragments/521.internal.md

According to the examples in the README of https://github.com/golangci/golangci-lint-action , it will use the go version used in `setup-go` action.

golang lint ci action: dont set go-version

---

newsfragments/531.internal.md
tests/integration/lib/utils.py

https://github.com/inyutin/aiohttp_retry/issues/114

Pytest aiohttp retry on exceptions : handle ClientResponseErrors

---

newsfragments/544.internal.md
pyproject.toml
scripts/towncrier_to_helm_annotation.py

Rather than alphabetical order, put the most important sections first
* `Security`
* `Deprecated`
* `Added`
* `Fixed`
* `Changed`
* `Removed`
Then finally for GitHub releases we also have `Internal`

Reorder changelog sections

---

.github/workflows/pytest.yml
newsfragments/547.internal.md

We may not want to test against the most recently created tag if that isn't in the history for a given commit. We want the nearest reachable tag.
Does `--match` so that we exclude anything that doesn't look like a release or is `matrix-tools-<version>`

Improve upgrade test tag detection

---

charts/matrix-stack/templates/matrix-rtc/sfu_deployment.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_rtc_udp_range_service.yaml
newsfragments/549.changed.md
newsfragments/549.fixed.md
tests/manifests/test_matrix_rtc.py
tests/manifests/test_pod_containers_ports.py
tests/manifests/test_services.py

Don't put more than 250 ports in a `Service` and don't put more than 100 UDP range ports on the Matrix RTC SFU pod

Handle wide Matrix RTC SFU UDP port ranges

---

charts/matrix-stack/configs/matrix-rtc/sfu/config-overrides.yaml.tpl
newsfragments/550.changed.md

`2025-06-11T13:32:20.648Z	WARN	livekit	service/server.go:146	prometheus_port is deprecated, please switch prometheus.port instead`

Remove warning about deprecated  config value in Matrix RTC SFU.

---

charts/matrix-stack/ci/fragments/matrix-rtc-exposed-services.yaml
charts/matrix-stack/ci/matrix-rtc-exposed-services-values.yaml
newsfragments/551.internal.md

Previously:
```sh
$ helm upgrade -i -n ess ess charts/matrix-stack -f charts/matrix-stack/ci/matrix-rtc-exposed-services-values.yaml 
Error: UPGRADE FAILED: failed to create resource: Service "ess-matrix-rtc-sfu-udp-range" is invalid: spec.ports[268].nodePort: Invalid value: 32768: provided port is not in the valid range. The range of valid ports is 30000-32767
$ helm upgrade -i -n ess ess charts/matrix-stack -f charts/matrix-stack/ci/matrix-rtc-exposed-services-values.yaml
Error: UPGRADE FAILED: cannot patch "ess-matrix-rtc-sfu-tcp" with kind Service: Service "ess-matrix-rtc-sfu-tcp" is invalid: spec.ports[0].nodePort: Invalid value: 33000: provided port is not in the valid range. The range of valid ports is 30000-32767 && cannot patch "ess-matrix-rtc-sfu-muxed-udp" with kind Service: …
```

Ensure example `NodePort` values use ports within `kind`'s `NodePort` range.

---

charts/matrix-stack/configs/synapse/path_map_file_get.tpl
charts/matrix-stack/templates/synapse/_synapse_details.tpl
newsfragments/557.fixed.md

Fixes https://github.com/element-hq/ess-helm/issues/556

matrixrtc: fix error when workers are enabled

---

README.md
newsfragments/567.fixed.md

It was raised in ESS Community room that it was not easy to find out remaining secrets & configmaps when one wants to reinstall without dropping the namespace : https://matrix.to/#/!RkXKfjpGXIVObpCqOI:element.io/$_IyhyBA5emCnVfSKICNL04_MXuHP11UU-YGQfq_VJjw?via=matrix.org&via=element.io&via=k8ekat.dev

document generated secret & deployment marker

---

charts/matrix-stack/ci/test-cluster-mixin.yaml
newsfragments/579.internal.md
tests/integration/fixtures/files/clusters/kind.yml

Makes it so that the authoriser service will work in the test cluster and that ports are open to work with the default SFU config

Improve the test cluster setup for Matrix RTC

---

.github/workflows/releasing.yml
newsfragments/591.changed.md

Fixes up from #586 as #589 couldn't do everything and introduced some of its own breakage

More CI fixes after pull_request switch

---

charts/matrix-stack/source/synapse.yaml.j2
charts/matrix-stack/values.yaml
newsfragments/577.changed.md

Draft as [RC](https://github.com/element-hq/synapse/releases/tag/v1.133.0rc1).
Changelog written as per release but image is RC

Upgrade Synapse to v1.133.0

---

charts/matrix-stack/source/matrixAuthenticationService.yaml.j2
charts/matrix-stack/values.yaml
newsfragments/578.changed.md

Draft as [RC](https://github.com/element-hq/matrix-authentication-service/releases/tag/v0.18.0-rc.0).
Changelog written as per release but image is RC

Upgrade MAS to v0.18.0

---

newsfragments/595.internal.md
tests/integration/test_networking.py

Let's see if this removes the flakes we have been seeing on components version upgrades.

ci: dont check services matching terminating pods

---

.github/workflows/templates-dyff.yml
newsfragments/602.internal.md

#586 removed  `with.ref: ${{ github.event.pull_request.head.sha }}` from `actions/checkout`. This had the impact of switching from checking out the HEAD of the PR to checking out a merge between the HEAD of the PR and the target branch. If there were changes on the target branch since the PR forked they would then show up in the `dyff`. Update the base branch to the current state of the target branch (by name rather than by SHA due to https://github.com/orgs/community/discussions/59677).
I have deliberately created this PR on a commit prior to the merge of #578 to see whether anything shows up or not

CI: change the comparision branch for the dyff job after the change to the source branch.

---

.github/workflows/templates-dyff.yml
newsfragments/606.internal.md

* Don't print all the metadata for added/removed files
* Highlight added/removed files

Improve template-dyff

---

charts/matrix-stack/configs/synapse/synapse-01-shared-underrides.yaml.tpl
newsfragments/609.changed.md

Implemented as an underride, so can be overridden by additional configuration. Just setting a more appropriate default

Synapse: default to TLS 1.2 or later for outbound federation

---

docs/advanced.md
newsfragments/617.added.md

See the conversation in the [ESS Community room](https://matrix.to/#/!RkXKfjpGXIVObpCqOI:element.io/$kvX8dpfZ4PSFEHArFrLaPMje7AZVwV22JaCLFbcOnWE?via=matrix.org&via=element.io&via=k8ekat.dev)

document traefik timeouts

---

README.md

Adds a link under the ESS Community section where folk can contact Element and upgrade to ESS Pro (& receive support)

Add ESS Pro upgrade link to README

---

charts/matrix-stack/source/synapse.yaml.j2
charts/matrix-stack/values.yaml
newsfragments/613.changed.md

https://github.com/element-hq/synapse/releases/tag/v1.134.0

Upgrade Synapse to v1.134.0

---

charts/matrix-stack/ci/example-default-enabled-components-checkov-values.yaml
charts/matrix-stack/ci/matrix-authentication-service-checkov-values.yaml
charts/matrix-stack/ci/matrix-authentication-service-minimal-values.yaml
charts/matrix-stack/ci/pytest-matrix-rtc-synapse-wellknown-values.yaml
charts/matrix-stack/ci/pytest-synapse-values.yaml
charts/matrix-stack/ci/synapse-checkov-with-workers-values.yaml
charts/matrix-stack/ci/synapse-minimal-values.yaml
newsfragments/621.internal.1.md
newsfragments/621.internal.2.md
newsfragments/621.internal.md
tests/integration/test_matrix_authentication_service.py
tests/integration/test_synapse.py

* Introduce `charts/matrix-stack/ci/example-default-enabled-components-checkov-values.yaml` so that we've something that covers `deploymentMarkers` explicitly
* Remove `deploymentMarkers` from `{synapse,matrix-authentication-service}-minimal-values.yaml` as removing them doesn't require additional values to be set
* At which point it also disappears from the corresponding `checkov` values file
* Remove `deploymentMarkers` from the Synapse based PyTests
* The `syn2mas` test covers starting with legacy auth
* The MAS PyTest does have `deploymentMarkers` available

Tweak CI values files

---

newsfragments/623.internal.md
scripts/assemble_ci_values_files_from_fragments.sh

If the order of fragments does matter, we don't want `no-changes-after-building` to fail because the fragments are now being applied in a different order, so sort before applying

Sort source_fragments before assembly to remove the chance of differences being generated on a subsequent run

---

.github/workflows/pytest.yml
charts/matrix-stack/ci/fragments/synapse-pytest-self-extras.yaml
charts/matrix-stack/ci/pytest-synapse-values.yaml
charts/matrix-stack/configs/synapse/partial-haproxy.cfg.tpl
newsfragments/632.fixed.md
tests/integration/lib/utils.py
tests/integration/test_synapse.py

Fixes #631. Regression from #508
HAProxy `acl`s don't appear to support multiple matches. It appears if multiple matches are specified (attempting to do ANDs), HAProxy silently accepts and just uses the final matcher.
Replace the `is_initial_sync` ACLs with multiple `http-request set-var(req.backend) str('initial-synchrotron')` to resolve.
Re-running the tests from #508 and adding a test based on #631 (logs and commands lightly edited for readability):
```
$ helm upgrade -i -n ess ess charts/matrix-stack -f charts/matrix-stack/ci/synapse-minimal-values.yaml --set 'synapse.workers.receipts-account.enabled=true' --set 'synapse.workers.initial-synchrotron.enabled=true' --set 'synapse.workers.synchrotron.enabled=true'
Release "ess" has been upgraded. Happy Helming!
...
$ curl -X POST …
```

Synapse: fix requests being routed to initial-synchrotron incorrectly

---

newsfragments/642.fixed.md
tests/integration/test_synapse.py

Fixes things like https://github.com/element-hq/ess-helm/actions/runs/16601437557/job/46961925846#step:12:124.
When upgrading Synapse can restart. We retry the 429's (present in the HAProxy logs as 503s), as can be seen by the fact that we don't fail at the `assert e.status in [401, 405]` line, however they will end up in the HAProxy logs, so just filter them out

Fix flakes in Synapse worker routing test

---

charts/matrix-stack/ci/fragments/synapse-all-workers-running.yaml
charts/matrix-stack/ci/synapse-worker-example-values.yaml
charts/matrix-stack/configs/matrix-authentication-service/config.yaml.tpl
charts/matrix-stack/configs/synapse/path_map_file_get.tpl
charts/matrix-stack/source/synapse.json
charts/matrix-stack/source/synapse.yaml.j2
charts/matrix-stack/templates/synapse/_synapse_details.tpl
charts/matrix-stack/values.schema.json
charts/matrix-stack/values.yaml
newsfragments/639.changed.1.md
newsfragments/639.changed.2.md
newsfragments/639.changed.md
newsfragments/639.fixed.md
tests/manifests/__init__.py

Relies on the following PRs:
* https://github.com/element-hq/synapse/pull/18581
* Some of the changes here show that the `receipts` event stream supports multiple workers, but it isn't documented as such. The `account_data` event stream doesn't and we currently bundle these 2 together. Enabling `receipts` as a scalable worker would require splitting the 2. Updating the documentation to make this obvious in https://github.com/element-hq/synapse/pull/18760 and implementing this in ESS in https://github.com/element-hq/ess-helm/pull/640
* Incorporates the pending documentation changes in https://github.com/element-hq/synapse/pull/18761 given matrix.org's configuration
* https://github.com/element-hq/synapse/pull/18716
* https://github.com/element-hq/synapse/pull/18520
* …

Upgrade to Synapse v1.135.0

---

charts/matrix-stack/configs/synapse/path_map_file.tpl
charts/matrix-stack/templates/synapse/_synapse_details.tpl
newsfragments/645.changed.md

Noticed whilst doing #644 that we don't need to maintain some lists, we can infer this from other (more vital) named templates.
This should be a no-op in terms of `dyff` or expose bugs

Simplify Synapse worker helpers

---

newsfragments/646.internal.md
tests/integration/test_synapse.py

`initial-synchtrotron` can fallback to `synchrotron` (if configured) or `main`. Other workers can fallback to `main`

CI: Accept routing to the failover backends in the Synapse routing test.

---

newsfragments/659.internal.md
tests/manifests/test_serviceaccounts.py

This simplifies the tests drastically by disabling all SA creation and checking that none exists.
We already verify `test_uses_serviceaccount_named_as_values_if_specified` and `test_uses_serviceaccount_named_as_per_pod_controller_by_default` so we dont need to check SA creation individually per component.

manifests tests: fix test does not create service account

---

charts/matrix-stack/configs/matrix-authentication-service/config.yaml.tpl
charts/matrix-stack/configs/synapse/partial-haproxy.cfg.tpl
charts/matrix-stack/configs/synapse/synapse-04-homeserver-overrides.yaml.tpl
charts/matrix-stack/source/common/sub_schema_values.yaml.j2
charts/matrix-stack/source/values.schema.json
charts/matrix-stack/templates/ess-library/_postgres.tpl
charts/matrix-stack/templates/synapse/_helpers.tpl
charts/matrix-stack/values.schema.json
charts/matrix-stack/values.yaml
newsfragments/692.changed.md
tests/manifests/test_haproxy.py
tests/manifests/test_services.py

Fixes #691 and also should reduce the DNS queries for these names 5-fold as the search domains are no longer considered

Support configuring a different cluster domain for internal Service references.

---

charts/matrix-stack/configs/synapse/partial-haproxy.cfg.tpl
charts/matrix-stack/templates/synapse/_helpers.tpl
newsfragments/715.added.md
tests/integration/test_synapse.py
tests/manifests/test_pod_idempotency.py

The admin API will want this.
This will cause the HAProxy `Pods` to restart on every chart version upgrade. The alternative is to accept that the version API could return incorrect results after upgrading or we need a sidecar process (that we don't have yet) to send the appropriate reload signal to HAProxy on the config changing

Expose the ESS version and edition in an API

---

charts/matrix-stack/source/matrix-rtc.yaml.j2
charts/matrix-stack/source/matrixAuthenticationService.yaml.j2
charts/matrix-stack/templates/matrix-authentication-service/_helpers.tpl
charts/matrix-stack/templates/matrix-authentication-service/deployment.yaml
charts/matrix-stack/templates/matrix-authentication-service/syn2mas_job.yaml
charts/matrix-stack/templates/matrix-rtc/sfu_deployment.yaml
charts/matrix-stack/values.yaml
newsfragments/723.changed.md
tests/manifests/test_matrix_authentication_service.py
tests/manifests/test_matrix_rtc.py

Do this to prevent clashing against multiple files in the same pod all named `config.yaml`.

Use unique file names for component configs

---

newsfragments/756.internal.md
tests/integration/test_syn2mas.py

Available since Synapse 1.138.0 / https://github.com/element-hq/synapse/pull/18549

Use stable URL for auth metadata

---

.github/element-docs-words.txt
charts/matrix-stack/source/matrix-rtc.yaml.j2
charts/matrix-stack/values.yaml
newsfragments/758.changed.md

https://github.com/livekit/livekit/releases/tag/v1.9.1
No particular reason, other than no particular reason to pin to 1.9.0

Matrix RTC SFU: upgrade to 1.9.1

---

charts/matrix-stack/ci/fragments/well-known-pytest-base-extras.yaml
charts/matrix-stack/ci/fragments/well-known-pytest-self-extras.yaml
charts/matrix-stack/ci/pytest-matrix-rtc-synapse-wellknown-values.yaml
charts/matrix-stack/ci/pytest-well-known-values.yaml
newsfragments/785.internal.md
tests/integration/test_well_known_delegation.py

`<component>-pytest-extras.yaml` only gets added to its own set of PyTests, not other components. When we need to split this between multiple components we do `<component>-pytest-base-extras.yaml` (which can be shared) and `<component>-pytest-self-extras.yaml` (which is not shared).
`/.well-known/element/element.json` was removed in https://github.com/element-hq/ess-helm/pull/641 but was missed in the tests thanks to the redirect

Remove well-known-pytest-extras.yaml from pytest-matrix-rtc-synapse-wellknown-values.yaml
