element-hq/ess-helm

- README.md
- newsfragments/344.added.md
Handcrafted by myself using some examples. Works on my side like this. Let me know if something's not needed.
> Add Apache2 reverse proxy config example

- charts/matrix-stack/templates/synapse/_helpers.tpl
- charts/matrix-stack/templates/synapse/_synapse_config.tpl
- newsfragments/345.fixed.md
- newsfragments/346.fixed.md
Lets avoid any reasoning about if any of those can diverge.
> synapse: use hostname for workername

- charts/matrix-stack/source/synapse.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/365.changed.md
https://github.com/element-hq/synapse/releases/tag/v1.128.0
> Upgrade Synapse to 1.128.0

- charts/matrix-stack/templates/ess-library/_labels.tpl
- newsfragments/385.fixed.md
Fixes https://github.com/element-hq/ess-helm/issues/377
> fix helm.sh/chart version label

- charts/matrix-stack/templates/element-web/_helpers.tpl
- charts/matrix-stack/templates/ess-library/_labels.tpl
- charts/matrix-stack/templates/haproxy/_helpers.tpl
- charts/matrix-stack/templates/init-secrets/_helpers.tpl
- charts/matrix-stack/templates/init-secrets/job.yaml
- charts/matrix-stack/templates/matrix-authentication-service/_helpers.tpl
- charts/matrix-stack/templates/matrix-rtc/_helpers.tpl
- charts/matrix-stack/templates/postgres/_helpers.tpl
- charts/matrix-stack/templates/synapse/_helpers.tpl
- charts/matrix-stack/templates/well-known/_helpers.tpl
- newsfragments/386.changed.md
> Clamp/restrict the app.kubernetes.io/version label too

- charts/matrix-stack/configs/element-web/config.json.tpl
- charts/matrix-stack/configs/matrix-authentication-service/config.yaml.tpl
- charts/matrix-stack/configs/synapse/synapse-04-homeserver-overrides.yaml.tpl
- newsfragments/387.internal.md
Minor regression from https://github.com/element-hq/ess-helm/pull/381
> synapse & element web: make sure serverName can use helm templates

- charts/matrix-stack/configs/element-web/config.json.tpl
- charts/matrix-stack/configs/synapse/synapse-log-config.yaml.tpl
- charts/matrix-stack/source/postgres.json
- charts/matrix-stack/source/postgres.yaml.j2
- charts/matrix-stack/templates/ess-library/_credentials.tpl
- charts/matrix-stack/templates/ess-library/_ingress.tpl
- charts/matrix-stack/templates/ess-library/_pods.tpl
- charts/matrix-stack/templates/ess-library/_serviceAccounts.tpl
- charts/matrix-stack/templates/matrix-authentication-service/_helpers.tpl
- charts/matrix-stack/templates/matrix-rtc/_helpers.tpl
- charts/matrix-stack/templates/postgres/_helpers.tpl
- charts/matrix-stack/templates/synapse/_helpers.tpl
- charts/matrix-stack/templates/synapse/synapse_check_config_job_hook.yaml
- charts/matrix-stack/templates/synapse/synapse_service.yaml
- charts/matrix-stack/templates/synapse/synapse_statefulset.yaml
- charts/matrix-stack/templates/well-known/_helpers.tpl
- charts/matrix-stack/values.schema.json
- charts/matrix-stack/values.yaml
- newsfragments/395.fixed.md
- scripts/ct-lint.sh
- tests/manifests/test_element_web.py
- tests/manifests/test_matrix_authentication_service.py
- tests/manifests/test_matrix_rtc.py
- tests/manifests/test_postgres.py
- tests/manifests/test_synapse.py
- tests/manifests/test_well_known_delegation.py
`merge` has some strange behaviour regarding boolean, and `true` will always win over `false`, even if it's not the dict with precedence.
See https://github.com/helm/helm/issues/5238
> Replace `merge` with `mergeOverwrite` to properly merge booleans.

- charts/matrix-stack/source/common/persistentVolumeClaim.json
- charts/matrix-stack/source/common/sub_schema_values.yaml.j2
- charts/matrix-stack/templates/postgres/pvc.yaml
- charts/matrix-stack/templates/synapse/synapse_persistentvolumeclaim.yaml
- charts/matrix-stack/values.schema.json
- charts/matrix-stack/values.yaml
- newsfragments/399.changed.md
- tests/manifests/__init__.py
- tests/manifests/test_pvcs.py
> Manage the helm.sh/resource-policy for PVCs

- newsfragments/411.internal.md
- poetry.lock
- pyproject.toml
Now that https://github.com/willemt/pytest-asyncio-cooperative/pull/68 is in a release
> Use released pytest-asyncio-cooperative

- charts/matrix-stack/source/element-web.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/428.changed.md
Changes: https://github.com/element-hq/element-web/compare/v1.11.97...v1.11.100#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed
> Element Web: Update to v1.11.100.

- charts/matrix-stack/templates/postgres/statefulset.yaml
- charts/matrix-stack/templates/synapse/redis_deployment.yaml
- newsfragments/435.changed.1.md
- newsfragments/435.changed.md
Tests coming in #430 but extracting these from that PR to minimise `dyff` output
> Add missing startupProbes

- .github/workflows/licensing.yml
- newsfragments/449.internal.md
This will help us keeping clean copyright headers dates.
> Check copyright dates in diffs

- newsfragments/455.changed.md
Describe the new versioning scheme.
> ess-helm new versioning scheme

- .github/workflows/changelog_check.yml
- newsfragments/473.internal.md
So that we can easily see what would be generated
> Add a job to preview the changelog for the next release

- charts/matrix-stack/source/element-web.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/475.changed.md
- scripts/check_newsfragment.sh
- scripts/towncrier_to_helm_annotation.py
https://github.com/element-hq/element-web/releases/tag/v1.11.101
> Element Web 1.11.101

- charts/matrix-stack/configs/synapse/path_map_file_get.tpl
- charts/matrix-stack/templates/synapse/_synapse_details.tpl
- newsfragments/479.changed.md
> Update worker paths for Synapse 1.130.0

- charts/matrix-stack/templates/NOTES.txt
- newsfragments/509.added.md
On main (before):
```
$ helm upgrade -i -n ess ess-foss charts/matrix-stack -f charts/matrix-stack/ci/example-default-enabled-components-values.yaml
Release "ess-foss" has been upgraded. Happy Helming!
NAME: ess-foss
LAST DEPLOYED: Tue Jun  3 11:49:57 2025
NAMESPACE: ess
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
ESS Community 
You are using ESS Community which is tailored to small-/mid-scale, non-commercial community use cases.
If you're looking for a professional Matrix backend that is designed to support enterprise requirements and certifications,
take a look at ESS Pro https://element.io/server-suite.
ESS Pro provides Long-Term Support releases, automatic scaling (horizontal and vertical) of Synapse Workers, Advanced Identity Management
to manage users and spaces …
```
> Improve NOTES.txt

- charts/matrix-stack/source/element-web.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/512.changed.md
https://github.com/element-hq/element-web/releases/tag/v1.11.102
> upgrade element web to v1.11.102

- charts/matrix-stack/configs/synapse/synapse-01-shared-underrides.yaml.tpl
- charts/matrix-stack/configs/synapse/synapse-04-homeserver-overrides.yaml.tpl
- newsfragments/513.changed.md
According to https://github.com/element-hq/element-call/blob/livekit/docs/self-hosting.md
> synapse: configure matrixRTC values

- charts/matrix-stack/templates/ess-library/_render_config.tpl
- charts/matrix-stack/templates/matrix-rtc/sfu_jwt_deployment.yaml
- charts/matrix-stack/templates/postgres/statefulset.yaml
- newsfragments/519.changed.md
- tests/manifests/test_volumes_mounts.py
Will merge after next FOSS Release
> index secret mounts based on hash of their names instead of an index

- README.md
- docs/maintenance.md
- newsfragments/584.changed.md
Follow-up to #567 as suggesting to delete things in the namespace and then delete the namespace felt odd.
Provide much more detail on the stateful components managed by the chart.
> More generated resources documentation

- newsfragments/629.internal.md
- tests/integration/lib/helpers.py
- tests/integration/test_networking.py
> wait for all replicasets to be ready

- charts/matrix-stack/source/matrixAuthenticationService.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/634.changed.md
https://github.com/element-hq/matrix-authentication-service/releases/tag/v0.20.0
> Upgrade Matrix Authentication Service to v0.20.0

- charts/matrix-stack/configs/matrix-rtc/sfu/config-overrides.yaml.tpl
- charts/matrix-stack/source/matrix-rtc.json
- charts/matrix-stack/source/matrix-rtc.yaml.j2
- charts/matrix-stack/templates/matrix-rtc/_helpers.tpl
- charts/matrix-stack/values.schema.json
- charts/matrix-stack/values.yaml
- newsfragments/635.changed.md
- tests/integration/fixtures/helm.py
- add `restrictRoomCreationToLocalUsers`, default to false
> matrix-authorisation-service: upgrade lk-jwt-service

- .github/workflows/pytest.yml
- newsfragments/661.internal.md
This is trying to fix https://github.com/element-hq/ess-helm/pull/660
> fix external contributors ci

- charts/matrix-stack/templates/synapse/_synapse_details.tpl
- newsfragments/685.fixed.md
Fixes #677
See https://github.com/element-hq/synapse/pull/18853 upstream
> Fix routing to workers for the room admin APIs

- README.md
- newsfragments/688.changed.md
As per https://github.com/element-hq/ess-helm/issues/686#issuecomment-3210883284 onwards
cc @HermannKroll
> Improve PostgreSQL docs in the README

- newsfragments/669.internal.md
- tests/integration/fixtures/helm.py
- tests/integration/lib/helpers.py
- tests/integration/test_networking.py
To fix things such as https://github.com/element-hq/ess-helm/actions/runs/16901759366/job/47882226641?pr=667
> add dockerhub secret to curl pods

- .github/workflows/scripts-linting.yml
> correctly spell cspell

- charts/matrix-stack/source/synapse.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/717.changed.md
Draft as RC. Changelog written as per release
> Update Synapse to v1.138.0

- .github/element-docs-words.txt
- charts/matrix-stack/source/element-web.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/739.changed.md
https://github.com/element-hq/element-web/releases/tag/v1.11.112
> Upgrade Element Web to v1.11.112

- charts/matrix-stack/source/synapse.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/755.changed.md
https://github.com/element-hq/synapse/releases/tag/v1.138.2
> Upgrade to Synapse 1.138.2

- charts/matrix-stack/source/element-admin.yaml.j2
- charts/matrix-stack/values.yaml
- newsfragments/759.added.md
This is for the bugfix in https://github.com/element-hq/element-admin/pull/73
> element-admin 0.1.2

- newsfragments/781.internal.md
- scripts/towncrier_to_helm_annotation.py
> Artifact Hub doesn't know about the doc type
